version: '2.4'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - "./web/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  client:
    image: node:16-alpine3.14
    environment:
      NODE_ENV: "development"
    working_dir: "/home/node/app"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/home/node/app:Z"
      - "client_node_modules:/home/node/app/node_modules"
    command: sh -c "chown node:node node_modules && npm i && npm run dev"
  server:
    image: node:16-alpine3.14
    environment:
      NODE_ENV: "development"
    working_dir: "/home/node/app"
    volumes:
      - "./server:/home/node/app:Z"
      - "server_node_modules:/home/node/app/node_modules"
    ports:
      - "5000:5000"
    command: sh -c "npm i && npm run dev"
volumes:
  client_node_modules:
  server_node_modules:
